//
// Created by 윤철중 on 2023/01/15.
//

#ifndef YOONFACTORY_ENUMS_H
#define YOONFACTORY_ENUMS_H

enum eStatus {
    STAT_NORMAL = 0,
    STAT_CONFORM,
    STAT_SEND,
    STAT_RECEIVE,
    STAT_USER,
    STAT_INSPECT,
    STAT_INFO,
    STAT_OK,
    STAT_NG,
    STAT_ERROR,
    STAT_COUNT
};

enum eDir2D {
    DIR_2D_NONE = 0,
    DIR_2D_CENTER,
    DIR_2D_TOP_LEFT,
    DIR_2D_TOP,
    DIR_2D_TOP_RIGHT,
    DIR_2D_RIGHT,
    DIR_2D_BOTTOM_RIGHT,
    DIR_2D_BOTTOM,
    DIR_2D_BOTTOM_LEFT,
    DIR_2D_LEFT,
    DIR_2D_COUNT
};

enum eDir2DMode {
    DIR_2D_MODE_FIXED = 0,
    DIR_2D_MODE_CLOCK4,
    DIR_2D_MODE_ANTI_CLOCK4,
    DIR_2D_MODE_CLOCK8,
    DIR_2D_MODE_ANTI_CLOCK8,
    DIR_2D_MODE_INCREASE,
    DIR_2D_MODE_DECREASE,
    DIR_2D_MODE_WHIRLPOOL,
    DIR_2D_MODE_ANTI_WHIRLPOOL,
    DIR_2D_MODE_AXIS_X,
    DIR_2D_MODE_AXIS_Y,
    DIR_2D_MODE_COUNT,
};

#endif //YOONFACTORY_ENUMS_H